### ISSUE TITLE
How to get predicted points?

### ISSUE THREAD

**Issue by dsm-72** [bunnech/jkonet#4]
If someone runs a task

```
python main.py --out_dir results --config_folder configs --task semicircle
```

How can they get (or just save) the predict points used to generate the figure predictions.png

**Comment by bunnech** [comment]
The figures are created here: https://github.com/bunnech/jkonet/blob/0a7f02835ba1d5344e47c7a1cc44246b2457a3b6/main.py#L208 Of course you can also simply save predictions. For this, have a look at the Numpy documentation: https://numpy.org/doc/stable/reference/generated/numpy.save.html?highlight=save#numpy.save.
